### ISSUE TITLE
Email message synchronization works incorrectly

### ISSUE THREAD

**Issue by imorenov94** [Haulmont/jmix-imap#19]
**Environment:**
OS: Win10
Jmix version: 1.0.2, 1.1.0-SNAPSHOT

**Steps:**
1. Create a new project with configurations from [README](https://github.com/haulmont/jmix-imap#readme)
2. Run the app and add a new mailbox from the IMAP configuration tab
3. Wait some time while quartz scheduler is complete and navigate to IMAP message browser tab
**ER:** All emails from the mailbox should be shown on the IMAP message browser tab
**AR:** All messages from the mailbox don't show in the message browser
**P.S:** It works each time differently, e.g on the first try can get messages only from the INBOX folder, but on the second try it can work correctly.

**Comment by m-orlova** [comment]
@imorenov94 Can't reproduce, waiting for more details about steps to reproduce the problem.

**Comment by imorenov94** [comment]
Currently it works correctly, maybe on that moment there were any issues with connection.
