### ISSUE TITLE
 Define Quartz scheduler beans inside the add-on

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-imap#7]
The quartz configuration for invoking the io.jmix.imap.ImapScheduler#syncImap must be added to the addon.

The task is similar to https://github.com/Haulmont/jmix-search/issues/53.

The application property `jmix.imap.useDefaultQuartzConfiguration` should enable the auto-configuration (default is **true**)
The application property `jmix.imap.imapSyncCron` will store a cron expression for the scheduler.

**Comment by DartVerder** [comment]
messages were not downloaded after the scheduller activate by setting the properties `jmix.imap.useDefaultQuartzConfiguration, jmix.imap.imapSyncCron` and adding the dependency ` implementation 'org.springframework.boot:spring-boot-starter-quartz'`
